dataset:
  train_files: Data/train_list_tiny_airplane.txt
  test_files: Data/test_list_tiny_airplane.txt
logging:
  save_dir: Data/logs/log_tiny_airplane
training:
  timeout: 240000
summaries:
  show_renders: True
  render: ['56c605d0b1bd86a9f417244ad1b14759', '8b594934c14ac5db66cf1b4a8fc3914e', '72d96bac651bc74c7af159eaf7625abf']
