dataset:
  train_files: Data/train_list_tiny.txt
  test_files: Data/test_list_tiny.txt
logging:
  save_dir: Data/logs/log_tiny
training:
  timeout: 2400
summaries:
  show_renders: True
  render: ['51670c355ece91abe24f4cc9bc86052a', '6bf75ddeac192594bda733a39f84326d']
